version: '3'

services:  
    
  db:
    image: mysql:5.7
    command: --innodb-use-native-aio=0
    container_name: db
    restart: always
    tty: true
    command: --init-file /data/application/init-mysql.sql
    volumes:
      - ./mysql:/var/lib/mysql
      - ./init-mysql.sql:/data/application/init-mysql.sql
    environment:
      - MYSQL_DATABASE=nodedb
      - MYSQL_ROOT_PASSWORD=root      
    networks:
      - node-network
      
  app:
    build: 
      context: node
    container_name: app
    entrypoint: dockerize -wait tcp://db:3306 -timeout 20s node index.js
    networks:
      - node-network
    volumes:
      - ./node:/usr/src/app
      - /usr/src/app/node_modules
    tty: true
    ports:
      - "3000:3000"
    depends_on:
      - db

  proxy:
    build: nginx
    container_name: proxy
    networks:
      - node-network
    volumes:
      - ./nginx:/usr/nginx
    tty: true
    ports:
      - "8080:80"
    depends_on:
      - app
  
networks:
  node-network:
    driver: bridge